### ISSUE TITLE
Add GA tracker

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/hev-e#13]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-149147181-1"> 
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-149147181-1');
    </script>

**Comment by simboss** [comment]
We are on it.

I will let you once it's done so you can test it.

**Comment by simboss** [comment]
It should be deployed see [this](view-source:http://assess-risk.info/#/).
Let us know if this works, @giohappy will take care of this if there issues.
