### ISSUE TITLE
adding layer to map

### ISSUE THREAD

**Issue by rmurnane** [GFDRR/hev-e#5]
one can only add a data set to the map from the listing of all data sets. Once a data set has been selected, and the graph information displayed, one needs to go back to the display of all data and then remember which data set was originally selected. 

Please make it so that a data set can be added (pinned) to the map from the graphics page (where you can select a data set for download).

**Comment by giohappy** [comment]
https://github.com/GFDRR/hev-e/commit/bbe6a243233eed0f09f3ad640d4d8fcbed5ee5cb
