### ISSUE TITLE
downloading vulnerability functions

### ISSUE THREAD

**Issue by rmurnane** [GFDRR/hev-e#9]
When downloading vulnerability function, on the download page the single file option should not be shown because it doesn't work (as far as I can tell).

**Comment by giohappy** [comment]
@rmurnane the download area is shared by all the datasets. That's the reason you see the single file option also when only vulnerabilities downloads have been added.
I will verify if we could disable it in case only vulnerabilities are being downloaded

**Comment by giohappy** [comment]
Single file is now disabled in case only vulnerabilities are selected for download
